### ISSUE TITLE
GameDev SK Tracker

### ISSUE THREAD

**Issue by phentos** [tritonhacks/TH24-NatureHuntStarter#1]
- [x] Complete & Import Rigged Character Assets
- [x] Complete & Import Static Object Assets
- [x] Complete OOP Programming guide in Doc, include helpful references
- [x] Complete C# + UnityEngine Scripting guide in Doc.
- [x] Implement basic animal pathfinding mechanics & animation controllers for hackers to tweak.
- [x] Implement random terrain generation mechanic for hackers to tweak.
- [ ] Create more variants of the assets currently imported into the project.
- [x] #2
- [ ] #3
